"""baseline: 4 张现存表（trajectories / compare_groups / compare_group_items / tool_steps）

基线迁移。两种环境的用法不同，不要混：

- 全新库（本地开发 / CI）：`alembic upgrade head` 真正执行，建出 4 张表 + 17 个索引。
- 已有数据的生产库：`alembic stamp 0001` —— 只写 alembic_version 表，不执行任何 DDL，
  含义是「这个库已经处于基线状态」。绝不能在生产跑本迁移的 upgrade（会 create_table 失败）。

已知漂移（本迁移会把它抹平）：旧的 `_migrate_sqlite_columns()` 只做 ADD COLUMN，
不建索引，所以经它升级过的库有 AI 评分列但缺 7 个对应索引
（idx_traj_ai_grade / ai_quality_status / deleted_at / device_id / score_version /
user_id / ix_trajectories_ai_score）。生产 PG 用 stamp 时需单独核对这批索引（用 `deploy/migrate.sh check` 验证是否漂移），补齐动作见 0002。


Revision ID: 0001
Revises: 
Create Date: 2026-09-04 01:03:39.572597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compare_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trajectories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('tool_source', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Text(), nullable=True),
    sa.Column('end_time', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_sent', sa.Integer(), nullable=True),
    sa.Column('tokens_received', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.REAL(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('total_api_calls', sa.Integer(), nullable=True),
    sa.Column('exit_status', sa.Text(), nullable=True),
    sa.Column('tools_used', sa.Text(), nullable=True),
    sa.Column('files_edited', sa.Text(), nullable=True),
    sa.Column('working_directory', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Text(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('quality_status', sa.Text(), nullable=True),
    sa.Column('quality_notes', sa.Text(), nullable=True),
    sa.Column('has_thinking', sa.Boolean(), nullable=True),
    sa.Column('has_sub_agent', sa.Boolean(), nullable=True),
    sa.Column('first_prompt', sa.Text(), nullable=True),
    sa.Column('traj_file_path', sa.Text(), nullable=False),
    sa.Column('traj_file_size', sa.Integer(), nullable=True),
    sa.Column('oss_key', sa.Text(), nullable=True),
    sa.Column('sha256', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_quality_status', sa.Text(), nullable=True),
    sa.Column('ai_grade', sa.Text(), nullable=True),
    sa.Column('rule_score', sa.Integer(), nullable=True),
    sa.Column('rule_details', sa.Text(), nullable=True),
    sa.Column('rule_flags', sa.Text(), nullable=True),
    sa.Column('heuristic_score', sa.Integer(), nullable=True),
    sa.Column('heuristic_details', sa.Text(), nullable=True),
    sa.Column('heuristic_patterns', sa.Text(), nullable=True),
    sa.Column('llm_score', sa.Integer(), nullable=True),
    sa.Column('llm_details', sa.Text(), nullable=True),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('llm_suggested_task_type', sa.Text(), nullable=True),
    sa.Column('llm_eval_model', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.Text(), nullable=True),
    sa.Column('score_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trajectories', schema=None) as batch_op:
        batch_op.create_index('idx_traj_ai_grade', ['ai_grade'], unique=False)
        batch_op.create_index('idx_traj_ai_quality_status', ['ai_quality_status'], unique=False)
        batch_op.create_index('idx_traj_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_traj_device_id', ['device_id'], unique=False)
        batch_op.create_index('idx_traj_exit_status', ['exit_status'], unique=False)
        batch_op.create_index('idx_traj_model', ['model'], unique=False)
        batch_op.create_index('idx_traj_project_name', ['project_name'], unique=False)
        batch_op.create_index('idx_traj_quality_status', ['quality_status'], unique=False)
        batch_op.create_index('idx_traj_score_version', ['score_version'], unique=False)
        batch_op.create_index('idx_traj_start_time', ['start_time'], unique=False)
        batch_op.create_index('idx_traj_task_type', ['task_type'], unique=False)
        batch_op.create_index('idx_traj_tool_source', ['tool_source'], unique=False)
        batch_op.create_index('idx_traj_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trajectories_ai_score'), ['ai_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_trajectories_session_id'), ['session_id'], unique=True)

    op.create_table('compare_group_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('trajectory_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['compare_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'trajectory_id')
    )
    op.create_table('tool_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trajectory_id', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=True),
    sa.Column('tool_input_summary', sa.Text(), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_steps', schema=None) as batch_op:
        batch_op.create_index('idx_steps_tool_name', ['tool_name'], unique=False)
        batch_op.create_index('idx_steps_traj_id', ['trajectory_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_steps', schema=None) as batch_op:
        batch_op.drop_index('idx_steps_traj_id')
        batch_op.drop_index('idx_steps_tool_name')

    op.drop_table('tool_steps')
    op.drop_table('compare_group_items')
    with op.batch_alter_table('trajectories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trajectories_session_id'))
        batch_op.drop_index(batch_op.f('ix_trajectories_ai_score'))
        batch_op.drop_index('idx_traj_user_id')
        batch_op.drop_index('idx_traj_tool_source')
        batch_op.drop_index('idx_traj_task_type')
        batch_op.drop_index('idx_traj_start_time')
        batch_op.drop_index('idx_traj_score_version')
        batch_op.drop_index('idx_traj_quality_status')
        batch_op.drop_index('idx_traj_project_name')
        batch_op.drop_index('idx_traj_model')
        batch_op.drop_index('idx_traj_exit_status')
        batch_op.drop_index('idx_traj_device_id')
        batch_op.drop_index('idx_traj_deleted_at')
        batch_op.drop_index('idx_traj_ai_quality_status')
        batch_op.drop_index('idx_traj_ai_grade')

    op.drop_table('trajectories')
    op.drop_table('compare_groups')
    # ### end Alembic commands ###
